### ISSUE TITLE
I can´t change the text Loading More.

### ISSUE THREAD

**Issue by FernandoPiche** [DevExpress-Examples/how-to-implement-the-load-more-functionality-t223734#1]

**Comment by mpreyskurantov** [comment]
Hello,

The final solution may depend on your specific requirements. We invite you to create a new ticket in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create) and share your current progress you have difficulties with. We will do our best to guide you.

**Comment by FernandoPiche** [comment]
Thanks, I´ll do it.
